# Generated by Django 2.2.1 on 2019-05-31 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
